### ISSUE TITLE
Complete Task

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [YoussefWaelMohamedLotfy/PasswordManagerAssessment#1]
The purpose of this project is to create a system for a company, to create and maintain their passwords for keeping login accounts into a simple website and CRUD the login list.

## Tasks

- [x]  The Project should be .net6 or .NET standard 2.0 (Domains)
- [x]  It should support creating, updating, and deleting Logins  
- [x]  The Project should use Encryption for saving the passwords
- [ ]  For the UI you should choose Blazor or Vue.js
- [x]  Your API should have Authorization and Authentication 
- [x]  Use AutoMapper and FluentValidation 
- [x]  Use Serilog for Logger
- [x]  The database should be SQL Code First
