### ISSUE TITLE
Change In-Memory store to EF Core Stores for IdentityServer

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [YoussefWaelMohamedLotfy/PasswordManagerAssessment#10]
The Configuration & Operational stores should be changed to use EF Core instead of In-Memory Stores.

## Tasks

- [x] Updates Configuration & Operational stores to use EF Core
- [x] Enable Consent for MVC Client
- [x] Integrate ASP.NET Core Identity with IdentityServer
