### ISSUE TITLE
Backend Implementation

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [YoussefWaelMohamedLotfy/PasswordManagerAssessment#3]
Referencing #1, this issue should complete the following tasks.

## Tasks
- [x]  It should support creating, updating, and deleting Logins
- [x] The Project should use Encryption for saving the passwords
- [x] Your API should have Authorization and Authentication
- [x] Use AutoMapper and FluentValidation
- [x] The database should be SQL Code First

A new Class Library is to be created for API Contracts and Swagger Examples which holds Data Transfer Objects (DTOs), that will be referenced in the API & SDK (in the future)
